-- MySQL Script generated by MySQL Workbench
-- Thu Jun 17 12:34:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema group_recommendations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema group_recommendations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `group_recommendations` DEFAULT CHARACTER SET utf8 ;
USE `group_recommendations` ;

-- -----------------------------------------------------
-- Table `group_recommendations`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`artist` (
  `spotify_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`spotify_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`user` (
  `spotify_id` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `spotify_id_UNIQUE` (`spotify_id` ASC) VISIBLE,
  PRIMARY KEY (`spotify_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`friends` (
  `user_spotify_id1` VARCHAR(45) NOT NULL,
  `user_spotify_id2` VARCHAR(45) NOT NULL,
  INDEX `fk_friends_user1_idx` (`user_spotify_id1` ASC) VISIBLE,
  INDEX `fk_friends_user2_idx` (`user_spotify_id2` ASC) VISIBLE,
  CONSTRAINT `fk_friends_user1`
    FOREIGN KEY (`user_spotify_id1`)
    REFERENCES `group_recommendations`.`user` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friends_user2`
    FOREIGN KEY (`user_spotify_id2`)
    REFERENCES `group_recommendations`.`user` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`playlist` (
  `spotify_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `link` VARCHAR(200) NOT NULL,
  `public` TINYINT NOT NULL,
  PRIMARY KEY (`spotify_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`song` (
  `spotify_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `accousticness` FLOAT NOT NULL,
  `danceability` FLOAT NOT NULL,
  `duration` INT NOT NULL,
  `energy` FLOAT NOT NULL,
  `instrumentalness` FLOAT NOT NULL,
  `key` INT NOT NULL,
  `liveness` FLOAT NOT NULL,
  `loudness` FLOAT NOT NULL,
  `mode` INT NOT NULL,
  `popularity` INT NOT NULL,
  `speechiness` FLOAT NOT NULL,
  `tempo` FLOAT NOT NULL,
  `time_signature` FLOAT NOT NULL,
  `valence` FLOAT NOT NULL,
  PRIMARY KEY (`spotify_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`playlist_has_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`playlist_has_song` (
  `playlist_spotify_id` VARCHAR(45) NOT NULL,
  `song_spotify_id` VARCHAR(45) NOT NULL,
  INDEX `fk_playlist_has_song_playlist1_idx` (`playlist_spotify_id` ASC) VISIBLE,
  INDEX `fk_playlist_has_song_song1_idx` (`song_spotify_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_has_song_playlist1`
    FOREIGN KEY (`playlist_spotify_id`)
    REFERENCES `group_recommendations`.`playlist` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_has_song_song1`
    FOREIGN KEY (`song_spotify_id`)
    REFERENCES `group_recommendations`.`song` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`top_artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`top_artist` (
  `user_spotify_id` VARCHAR(45) NOT NULL,
  `artist_spotify_id` VARCHAR(45) NOT NULL,
  `rank` INT NOT NULL,
  INDEX `fk_top_artist_user1_idx` (`user_spotify_id` ASC) VISIBLE,
  INDEX `fk_top_artist_artist1_idx` (`artist_spotify_id` ASC) VISIBLE,
  CONSTRAINT `fk_top_artist_user1`
    FOREIGN KEY (`user_spotify_id`)
    REFERENCES `group_recommendations`.`user` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_top_artist_artist1`
    FOREIGN KEY (`artist_spotify_id`)
    REFERENCES `group_recommendations`.`artist` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`top_track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`top_track` (
  `rank` INT NOT NULL,
  `user_spotify_id` VARCHAR(45) NOT NULL,
  `song_spotify_id` VARCHAR(45) NOT NULL,
  INDEX `fk_top_track_user1_idx` (`user_spotify_id` ASC) VISIBLE,
  INDEX `fk_top_track_song1_idx` (`song_spotify_id` ASC) VISIBLE,
  CONSTRAINT `fk_top_track_user1`
    FOREIGN KEY (`user_spotify_id`)
    REFERENCES `group_recommendations`.`user` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_top_track_song1`
    FOREIGN KEY (`song_spotify_id`)
    REFERENCES `group_recommendations`.`song` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `group_recommendations`.`user_has_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_recommendations`.`user_has_playlist` (
  `user_spotify_id` VARCHAR(45) NOT NULL,
  `playlist_spotify_id` VARCHAR(45) NOT NULL,
  INDEX `fk_user_has_playlist_user1_idx` (`user_spotify_id` ASC) VISIBLE,
  INDEX `fk_user_has_playlist_playlist1_idx` (`playlist_spotify_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_playlist_user1`
    FOREIGN KEY (`user_spotify_id`)
    REFERENCES `group_recommendations`.`user` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_playlist_playlist1`
    FOREIGN KEY (`playlist_spotify_id`)
    REFERENCES `group_recommendations`.`playlist` (`spotify_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;